zheqi - delete importing ase_rdmol
Buttsgroup/EMS pull request #3
Opened 2024-09-04 23:08 UTC by Bread-Jim

Delete the _ase_rdmol_ imported from _modules.properties.structure_io_ because there is no _ase_rdmol_ function in the _structure_io_ package.

2024-09-05 13:17 UTC, CalvinCYY requested changes
Setup an initial test_EMS.py file for asserting code functionality

2024-09-05 13:17 UTC, CalvinCYY commented on EMS.py
> +print(len(mol.type))
Move this into a test_EMS.py script under the tests folder to avoid cluttering the class and for functionality with Pytest

2024-09-05 17:03 UTC, Bread-Jim commented
There is an additional __pycache__ file. Is it to be kept or make into .gitignore?

2024-09-10 13:23 UTC, Benhonore approved these changes

2024-09-10 13:24 UTC, Benhonore approved these changes

2024-09-12 13:28 UTC, CalvinCYY approved these changes

2024-09-12 13:28 UTC, merged